# Default values for compss-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: oriolmac/compss-elixirion
  pullPolicy: IfNotPresent
  tag: latest

mqtt:
  enabled: false
  image:
    repository: oriolmac/mqtt-broker
    tag: latest
    pullPolicy: Always
  port: 1883
  nodePort: 31883

compss:
  # namespace: {}
  master:
    labels:
      node: master
    ports:
      name: ssh
    # local volume in node where the master is executed
    volume: {}
    #  localPath: /home/minikube  # previously mounted with minikube mount and existing locally
    #  node: minikube # Minikube name, by default minikube
    prometheusClient: 
      enabled: false
      buckets: "-inf, 0.0001, 0.0005, 0.001, 0.0025, 0.005, 0.01, 0.1, 1, 10, 50, 100, 200, inf" # Histogram bucket
      containerPort: 15000
      redisContainerPort: 6379

    scheduler_config:
    #  vertical_scalability: "true"
    #  vertical_increasing_cpus: 2 # (integer)

  worker:
    number: 1  # total worker pods
    labels:
      node: worker
    resources:
      cpu: 1  # CPUs per worker
      memory: 2  # GiB per worker
    ports:
      name: ssh
    prometheusClient: 
      enabled: false
      buckets: "-inf, 0.0001, 0.0005, 0.001, 0.0025, 0.005, 0.01, 0.1, 1, 10, 50, 100, 200, inf" # Histogram bucket
      containerPort: 15000
      redisContainerPort: 6379

  service:
    ssh: 22

monitoring:
  enabled: true
  port: 15000
  prometheusUrl: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
  image:
    repository: oriolmac/monitoring-api
    tag: latest
    pullPolicy: Always
  servicemonitor:
    releaseName: prometheus
  namespace: monitoring
  node:

app:
  context:
    folderPath: /home/omartinez/elixiron-school/apps
    file: app.py
  params:
    ### Example Matmul application parameters ###
    #num_blocks: "3"
    #elems_per_block: "1024"
    #number_iterations: "1"

    ### Example Genetic algorithm application parameters ###
    #num_individuals: "100"
    #size: "100"
    #target: "200"
    #lifecycles: "10"
    #get-fitness: "False"
    #iterations: "15"
    #sleep_tasks: "4"

    ### Example Cholesky application parameters ###
    #matrix_size: "4"
    #block_size: "256"
    #sleep_tasks: "4"




